### PR TITLE
Fix the name of rust-toolchain.toml

### PR DESCRIPTION
**Pull request by gfx**
The name `rust-toolchain` does not work in my environment. I'm not sure the why, but [the doc](https://rust-lang.github.io/rustup/overrides.html) says `rust-toolchain.toml` is the new name, and `rust-toolchain` "is used for backwards compatibility". Once renamed, `rustc` works well. 

before:

```shell-session
$ rustc --version
error: invalid channel name '[toolchain]' in '/Users/goro-fuji/ghq/github.com/fastly/compute-starter-kit-rust-default/rust-toolchain'
info: caused by: invalid toolchain name: '[toolchain]'
```

after:
```
rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

## Environment

* macOS 11.6.1
* cargo `1.57.0 (b2e52d7ca 2021-10-21)`
* Fastly CLI version `1.3.0 (0a365cb)`

### CODE REVIEW

**Comment by fgsch** [comment]
What is your rustup version?

**Comment by gfx** [comment]
`rustup 1.24.3 (2021-05-31)`

**Comment by gfx** [comment]
> `error: invalid channel name '[toolchain]' in '/PATH/TO/DIRECTORY/rust-toolchain`
> it means you're running rustup pre-1.23.0 and trying to interact with a project that uses the new TOML encoding in the rust-toolchain file. You need to upgrade rustup to 1.23.0+.

So my error seems odd. More oddly, renaming the file solves my error.

**Comment by fgsch** [comment]
I have the same versions and this works fine with the current naming. 
Reinstalling rustup should do the trick but perhaps renaming it is the right fix, I don't know.

Fwiw, we also had this issue with the cli: https://github.com/fastly/cli/issues/137.

**Comment by gfx** [comment]
Re-installed `rustup` (it's actually `rustup-init` in homebrew macOS), but nothing has changed. 

Hopefully this PR fixes the long-standing riddle.

**Comment by gfx** [comment]
There is  still the same problem on my env with new toolchains:

* Fastly CLI version v3.3.0 (96b3aa7)
* rustc 1.61.0 (fe5b13d68 2022-05-18)
* rustup 1.25.1 (2022-07-12)
* macOS 11.6.8

I think this PR is good enough anyway, as the rustup's doc describes the toolchain config as `rust-toolchain.toml`.

**Comment by jameysharp** [comment]
Double-checking rustup's changelog, I see that the structured format for `rust-toolchain` was introduced in 1.23.0, and support for naming the file `rust-toolchain.toml` was added in 1.24.0. Since the latter was released over a year ago, and very few package repositories have 1.23.* (according to [Repology](https://repology.org/project/rustup/versions)), I personally think it's reasonable to merge this PR.

**Review by Integralist — APPROVED** [review]
LGTM. Let's change this in all our Rust starter kits.

**Comment by gfx** [comment]
Thank you. I've confirmed that a project initialized by `fastly compute init` works without changes 👏

**Pull request merged**
