### PR TITLE
🚀 update to `fastly-0.5.0`

### PR DESCRIPTION
**Pull request by cratelyn**
### Changes

* Update default template's `fastly` dependency to `^0.5.0`

* Update lockfile

* Use new `RequestExt::cache_override_mut` API for setting cache
  overrides. See the documentation of this method here:
  https://docs.rs/fastly/0.5.0/fastly/request/trait.RequestExt.html#method.cache_override_mut

### CODE REVIEW

**Comment by cratelyn** [comment]
Once merged, we should add a `0.5.0` branch that the CLI can use to pull this new updated template.

**Comment by cratelyn** [comment]
As mentioned [here](https://github.com/fastly/ExecuteD/pull/571#issuecomment-716052791), I have some outstanding questions regarding whether or not the `fastly-sys-0.3.5` troubles require a `fastly-0.5.1`. I'd like to figure that out before we merge this and incorporate it into the CLI.

**Review by phamann — APPROVED** [review]
LGTM 👍

**Review by acfoltzer — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
